---
- name: template module demo
  hosts: all
  vars:
    fruit: "apple"
    output: "output-template.txt"
  tasks:
    - name: write to a file 
      ansible.builtin.template:
        src: "/home/sbose/ansible-tutorials/write_variable_to_a_file/mytemplate.j2"
        dest: "/home/sbose/ansible-tutorials/write_variable_to_a_file/{{ output }}"
