---
- name: Date, Time and Timestamp demo
  hosts: all
  gather_facts: true
  tasks:
    - name: date and time
      ansible.builtin.debug:
        var: ansible_date_time
    
    - name: ISO 8601 formatted date and time
      ansible.builtin.debug:
        var: ansible_date_time.iso8601
    