---
- name: tags demo
  hosts: all
  gather_facts: false
  tasks:
    - name: example1 
      ansible.builtin.debug:
        msg: "example 1"
      tags: tag1

    - name: example2
      ansible.builtin.debug:
        msg: "example 2"
      tags: tag2