---
- name: select attribute demo 
  hosts: all
  gather_facts: true
  tasks:
    - name: all features 
      ansible.builtin.debug:
        var: 'ansible_facts.eth0.features'

    - name: filter enabled 
      ansible.builtin.debug:
        msg: "{{ (ansible_facts.eth0.features | dict2items | selectattr('value', 'match', 'on')) }}"